name: "go'touch't"
favicon: null
layout_spectrum: 0.65258
typography_spectrum: 0.48594733187928796
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004776'
    - '#f7e3c8'
    - '#83adc2'
    - '#5c8ba4'
    - '#010103'
  brandStrength: 0
  lightness: 0.5812062011100352
  saturation: 0.1037390036508441
  rhythmicContrast: 0.3982453220523894
purpose: []
