name: gotoucht
favicon: null
layout_spectrum: 0.5496640068013221
typography_spectrum: 0.48594733187928796
title: "GO'TOUCH'T"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.5812062011100352
  saturation: 0.1037390036508441
  rhythmicContrast: 0.3982453220523894
purpose: []
