name: "go'touch't"
favicon: null
layout_spectrum: 0.67622
typography_spectrum: 0.48594733187928796
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004678'
    - '#f8e4c6'
    - '#5b8aa6'
    - '#000203'
    - '#d4b494'
  brandStrength: 0
  lightness: 0.5812062011100352
  saturation: 0.1037390036508441
  rhythmicContrast: 0.3982453220523894
purpose: []
